jobs:
  include:
    - os: linux
      dist: trusty
      script:
        - sudo apt install -y ca-certificates openssl
        - sudo update-ca-certificates
        - sudo apt-install --only-upgrade openssl
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: xenial
      script:
        - sudo apt install -y ca-certificates openssl
        - sudo update-ca-certificates
        - sudo apt-install --only-upgrade openssl
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: bionic
      script:
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: focal
      script:
        - curl https://asset-packagist.org/packages.json
        - echo done
