jobs:
  include:
    - os: linux
      dist: trusty
      script:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: xenial
      #language: ruby
      #ruby:
      #  - 3.0
      before_install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        - curl https://asset-packagist.org/packages.json
        - echo done
    - os: linux
      dist: bionic
      language: java
      jdk: openjdk15
      install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: focal
      language: php
      php:
        - 7.4
      install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        - curl https://asset-packagist.org/packages.json
        - wget http://pecl.php.net/get/memcached-3.1.5.tgz
        - pear install memcache-3.0.6.tgz
    - os: osx
      osx_image: xcode11.4
      language: ruby
      ruby:
        - 2.7
      addons:
        homebrew:
          update: true
      script: true
    - os: linux
      dist: focal
      language: node_js
      node_js:
        - 10
      addons:
        - rethinkdb: '2.3.6'
      before_install:
        - sudo apt-get update && sudo apt-get install apt-transport-https ca-certificates -y && sudo update-ca-certificates
      script: true
    - os: linux
      dist: focal
      language: node_js
      node_js:
        - 12
      addons:
        - rethinkdb: '2.3.6'
      before_install:
        - sudo apt-get update && sudo apt-get install apt-transport-https ca-certificates -y && sudo update-ca-certificates
      script: true
