os: linux
dist: precise
jobs:
  include:
    - dist: precise
      os: linux
      arch: amd64
      language: php
      php: 5.3
      before_install:
        - apt-get update
        - composer self-update
      script: true
      
    - dist: precise
      os: linux
      arch: amd64
      language: php
      php: 5.4
      before_install:
        - apt-get update
        - composer self-update
      script: true
