jobs:
  include:
    - dist: bionic
      os: linux
      arch: amd64
      virt: lxd
      language: php
      php: 5.3
      before_install:
        - composer self-update
      script: true
      
    - dist: bionic
      os: linux
      arch: amd64
      virt: lxd
      language: php
      php: 5.4
      before_install:
        - composer self-update
      script: true
