jobs:
  include:
    - os: linux
      dist: trusty
      script:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: xenial
      #language: ruby
      #ruby:
      #  - 3.0
      before_install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        - curl https://asset-packagist.org/packages.json
        - echo done
    - os: linux
      dist: bionic
      language: java
      jdk: openjdk12
      install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: focal
      language: ruby
      ruby:
        - 3.0
      install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        - curl https://asset-packagist.org/packages.json
