jobs:
  include:
    - dist: focal
      os: linux
      arch: amd64
      virt: lxd
      language: node_js
      node_js: 12.4
      
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm i yarn -g; fi

      script: true
      
    - osx_image: xcode9.1
      os: osx
      language: node_js
      node_js: 12.4
      
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm i yarn -g; fi

      script: true
      
    - osx_image: xcode9.4
      os: osx
      language: node_js
      node_js: 12.4
      
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm i yarn -g; fi

      script: true
