jobs:
  include:
    - dist: focal
      os: linux
      arch: amd64
      virt: lxd
      language: ruby

      script: true
      
    - os: linux
      dist: trusty
      script:
        #- sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: xenial
      language: ruby
      ruby:
        - 3.0
      #before_install:
        #- sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        - curl https://asset-packagist.org/packages.json
        - echo done
    - os: linux
      dist: bionic
      language: java
      jdk: openjdk15
      #install:
        #- sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        #- sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: focal
      language: php
      php:
        - 7.4
      #install:
        #- sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script:
        - curl https://asset-packagist.org/packages.json
        - wget http://pecl.php.net/get/memcached-3.1.5.tgz
        - echo "no --disable-memcached-sasl" | pear install memcached-3.1.5.tgz
