jobs:
  include:
    - os: linux
      dist: trusty
      before_install:
        - wget --no-check-certificate https://www.openssl.org/source/old/1.1.0/openssl-1.1.0g.tar.gz
        - tar xzvf openssl-1.1.0g.tar.gz
        - cd openssl-1.1.0g
        - ./config
        - make
        - sudo make install
      script:
        - sudo update-ca-certificates
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: xenial
      before_install:
        - wget --no-check-certificate https://www.openssl.org/source/old/1.1.0/openssl-1.1.0g.tar.gz
        - tar xzvf openssl-1.1.0g.tar.gz
        - cd openssl-1.1.0g
        - ./config
        - make
        - sudo make install
      script:
        - sudo update-ca-certificates
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: bionic
      script:
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: focal
      script:
        - curl https://asset-packagist.org/packages.json
        - echo done
