jobs:
  include:
    - os: linux
      dist: trusty
      script:
        - sudo apt-get update
        - sudo apt install -y ca-certificates openssl_1.0.2g
        - sudo update-ca-certificates
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: xenial
      script:
        - sudo apt-get update
        - sudo apt install -y ca-certificates openssl_1.0.2g
        - sudo update-ca-certificates
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: bionic
      script:
        - curl https://asset-packagist.org/packages.json
    - os: linux
      dist: focal
      script:
        - curl https://asset-packagist.org/packages.json
        - echo done
